image:
  - Visual Studio 2019
  - Visual Studio 2022
version: 1.9.0.{build}
platform:
  - Any CPU
configuration:
  - Release

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
    - nuget pack nunit-template.nuspec
    - dotnet new -i ./*.nupkg
    - dotnet --info

    # unfortunately, F# under full .NET Framework issues a compilation error, the issue is in F# compiler
    - dotnet new nunit -n CSharpNet35  --framework net35 -lang c#
    - dotnet new nunit -n VBasicNet35  --framework net35 -lang vb

    - dotnet new nunit -n CSharpNet40  --framework net40 -lang c#
    - dotnet new nunit -n VBasicNet40  --framework net40 -lang vb

    - dotnet new nunit -n CSharpNet45  --framework net45 -lang c#
    - dotnet new nunit -n VBasicNet45  --framework net45 -lang vb

    - dotnet new nunit -n CSharpNet451 --framework net451 -lang c#
    - dotnet new nunit -n VBasicNet451 --framework net451 -lang vb

    - dotnet new nunit -n CSharpNet452 --framework net452 -lang c#
    - dotnet new nunit -n VBasicNet452 --framework net452 -lang vb

    - dotnet new nunit -n CSharpNet46  --framework net46 -lang c#
    - dotnet new nunit -n VBasicNet46  --framework net46 -lang vb

    - dotnet new nunit -n CSharpNet461 --framework net461 -lang c#
    - dotnet new nunit -n VBasicNet461 --framework net461 -lang vb

    - dotnet new nunit -n CSharpNet462 --framework net462 -lang c#
    - dotnet new nunit -n VBasicNet462 --framework net462 -lang vb

    - dotnet new nunit -n CSharpNet47 --framework net47 -lang c#
    - dotnet new nunit -n VBasicNet47 --framework net47 -lang vb

    - dotnet new nunit -n CSharpNet471 --framework net471 -lang c#
    - dotnet new nunit -n VBasicNet471 --framework net471 -lang vb

    - dotnet new nunit -n CSharpNet472 --framework net472 -lang c#
    - dotnet new nunit -n VBasicNet472 --framework net472 -lang vb

    - dotnet new nunit -n CSharpNet48 --framework net48 -lang c#
    - dotnet new nunit -n VBasicNet48 --framework net48 -lang vb

    - dotnet new nunit -n CSharpNetCore31  --framework netcoreapp3.1 -lang c#
    - dotnet new nunit -n FSharpNetCore31  --framework netcoreapp3.1 -lang f#
    - dotnet new nunit -n VBasicNetCore31  --framework netcoreapp3.1 -lang vb

  test_script:
    - msbuild /p:FrameworkPathOverride="%programfiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client" CSharpNet35
    - msbuild /p:FrameworkPathOverride="%programfiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client" VBasicNet35
    - dotnet test CSharpNet35 --no-build
    - dotnet test VBasicNet35 --no-build

    - dotnet test CSharpNet40
    - dotnet test VBasicNet40

    - dotnet test CSharpNet45
    - dotnet test VBasicNet45

    - dotnet test CSharpNet451
    - dotnet test VBasicNet451

    - dotnet test CSharpNet452
    - dotnet test VBasicNet452

    - dotnet test CSharpNet46
    - dotnet test VBasicNet46

    - dotnet test CSharpNet461
    - dotnet test VBasicNet461

    - dotnet test CSharpNet462
    - dotnet test VBasicNet462

    - dotnet test CSharpNet47
    - dotnet test VBasicNet47

    - dotnet test CSharpNet471
    - dotnet test VBasicNet471

    - dotnet test CSharpNet472
    - dotnet test VBasicNet472

    - dotnet test CSharpNet48
    - dotnet test VBasicNet48

    - dotnet test CSharpNetCore31
    - dotnet test FSharpNetCore31
    - dotnet test VBasicNetCore31
  artifacts:
    - path: '*.nupkg'

-
  matrix:
    only:
      - image: Visual Studio 2022

  build_script:
    - nuget pack nunit-template.nuspec
    - dotnet new -i ./*.nupkg
    - dotnet --info'

    - dotnet new nunit -n CSharpNetCore50 --framework net5.0 -lang c#'
    - dotnet new nunit -n FSharpNetCore50 --framework net5.0 -lang f#'
    - dotnet new nunit -n VBasicNetCore50 --framework net5.0 -lang vb'

    - dotnet new nunit -n CSharpNetCore60 --framework net6.0 -lang c#'
    - dotnet new nunit -n FSharpNetCore60 --framework net6.0 -lang f#'
    - dotnet new nunit -n VBasicNetCore60 --framework net6.0 -lang vb'

  test_script:
    - dotnet test CSharpNetCore50'
    - dotnet test FSharpNetCore50'
    - dotnet test VBasicNetCore50'

    - dotnet test CSharpNetCore60'
    - dotnet test FSharpNetCore60'
    - dotnet test VBasicNetCore60'
  artifacts:
    - path: '*.nupkg'
